name: build
on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python 2.7.18
        run: |
          wget https://github.com/dkruben/setup-python/releases/download/2.7.18/python_2.7.18-1_amd64.deb
          sudo apt install ./python_2.7.18-1_amd64.deb -y --allow-downgrades
      - name: Clone repo
        uses: actions/checkout@master

      - name: Build recent-stat
        run: python2 build.py
      - name: Upload recent-stat artifact
        uses: actions/upload-artifact@v2
        with:
          name: recent-stat
          path: build/*
          if-no-files-found: error

      - name: Build recent-stat-badges
        run: |
          cd badgesModifier
          pip3 install -r requirements.txt
          ./modifyBadges.sh
      - name: Upload recent-stat-badges artifact
        uses: actions/upload-artifact@v2
        with:
          name: recent-stat-badges
          path: badgesModifier/build/*
          if-no-files-found: error
